### ISSUE TITLE
Problem with apply function because of missing attribute "original_shape"

### ISSUE THREAD

**Issue by sebi06** [Rignak/MightyMosaic#1]
Hi i tried our this cool tool by applying a trained TF2 model, but get an error about a missing attribute original_shape. Is this a bug or my mistake?

```bash
(imageanalysis) C:\Users\m1srh\Documents\GitHub\ipy_notebooks\cellpose>C:/ProgramData/Anaconda3/envs/imageanalysis/python.exe c:/Users/m1srh/Documents/GitHub/ipy_notebooks/cellpose/cellpose_regionprops_srh.py
2020-04-09 08:47:51.539815: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
ZEN TF Model Tile Dimension :  1024 1024
Analyzing S-T-Z-C:  0 0 0 0
image2d_tiled shape :  (2, 2, 1024, 1024)
image2d_tiled shape + newaxis:  (2, 2, 1024, 1024, 1)
  0%|                                                                                                                                       | 0/4 [00:00<?, ?it/s]2020-04-09 08:47:57.136015: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-09 08:47:57.154927: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-09 08:47:57.197149: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] model_pruner failed: Invalid argument: MutableGraphView::MutableGraphView
error: node 'model/cond/else/_1/StatefulPartitionedCall/StatefulPartitionedCall/unet_neon/lambda/concat' has self cycle fanin 'model/cond/else/_1/StatefulPartitionedCall/StatefulPartitionedCall/unet_neon/lambda/concat'.
2020-04-09 08:47:57.230987: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] remapper failed: Invalid argument: MutableGraphView::MutableGraphView error: node 'model/cond/else/_1/StatefulPartitionedCall/StatefulPartitionedCall/unet_neon/lambda/concat' has self cycle fanin 'model/cond/else/_1/StatefulPartitionedCall/StatefulPartitionedCall/unet_neon/lambda/concat'.
2020-04-09 08:47:57.255116: E tensorflow/core/grappler/optimizers/meta_optimizer.cc:502] arithmetic_optimizer failed: Invalid argument: The graph couldn't be sorted in topological order.
2020-04-09 08:47:57.269047: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 0, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-09 08:47:57.285251: E tensorflow/core/grappler/optimizers/dependency_optimizer.cc:697] Iteration = 1, topological sort failed with message: The graph couldn't be sorted in topological order.
2020-04-09 08:47:57.304621: W tensorflow/core/common_runtime/process_function_library_runtime.cc:675] Ignoring multi-device function optimization failure: Invalid
argument: The graph couldn't be sorted in topological order.
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 4/4 [00:21<00:00,  5.36s/it]
Traceback (most recent call last):
  File "c:/Users/m1srh/Documents/GitHub/ipy_notebooks/cellpose/cellpose_regionprops_srh.py", line 424, in <module>
    mindist_ws=min_peakdist)
  File "c:/Users/m1srh/Documents/GitHub/ipy_notebooks/cellpose/cellpose_regionprops_srh.py", line 203, in segment_zentf_tiling
    prediction_tiled = image2d_tiled.apply(model.predict, progress_bar=True, batch_size=1)[0]
  File "C:\ProgramData\Anaconda3\envs\imageanalysis\lib\site-packages\MightyMosaic\MightyMosaic.py", line 119, in apply
    new_shape = [self.original_shape[0] // (self.shape[2] // patchs[0][2].shape[0]),
AttributeError: 'MightyMosaic' object has no attribute 'original_shape'

(imageanalysis) C:\Users\m1srh\Documents\GitHub\ipy_notebooks\cellpose>
```

**Comment by AurelienColin** [comment]
Hi.
It's strange because _original_shape_ is defined in the `__new__`  method of the class. 
Can you provide me the lines that were used to defined the MightMosaic object ?
